apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress-httpserver
spec:
  rules:
  - host: httpserver.io
    http:
      paths:
      - path: "/status"
        pathType: Prefix
        backend:
          service:
            name:  httpserver
            port:
              number: 80